[workspace]
resolver = "3"

members = ["crates/blockguard-chain",
    "crates/blockguard-core",
    "crates/blockguard-crypto",
    "crates/blockguard-state",
    "crates/blockguard-chain", 
    "crates/blockguard-consensus",
    "crates/blockguard-storage",
    "crates/blockguard-mempool",
    "crates/blockguard-node",
    "crates/blockguard-network",
]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
blockguard-core = { path = "crates/blockguard-core" }
blockguard-crypto = { path = "crates/blockguard-crypto" }
blockguard-state = { path = "crates/blockguard-state" }
blockguard-chain = { path = "crates/blockguard-chain" }
blockguard-consensus = { path = "crates/blockguard-consensus" }
blockguard-storage = { path = "crates/blockguard-storage" }
blockguard-mempool = { path = "crates/blockguard-mempool" }
blockguard-node = { path = "crates/blockguard-node" }
blockguard-network = { path = "crates/blockguard-network" }
sha2 = "0.11"
k256 = { version = "0.14", features = ["ecdsa", "sha256", "getrandom"] }
primitive-types = { version = "0.13", default-features = false }
